name: AWS Infra

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/infra-deploy.yaml
      - "packages/infra/tf/**"
      - "!packages/infra/tf/**.md" 
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/infra-deploy.yaml
      - "packages/infra/tf/**"
      - "!packages/infra/tf/**.md" 

defaults:
  run:
    working-directory: packages/infra/tf

env:
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}

jobs:
  build_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.6

      - name: Terraform format checking
        run: terraform fmt -recursive -check

      - name: Initialise and plan changes for DEV
        run: make init && make plan_ci
        env:
          ENVIRONMENT: dev

  deploy_dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: build_dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.6
      
      - name: Apply Infra changes for DEV
        run: make init && make apply
        env:
          ENVIRONMENT: dev
          TF_AUTO_APPROVE: --auto-approve